version: '3.3'

services:
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/app
    restart: always
    command: bash -c "npm install && npm run debug"
    volumes:
      - ./dist/:/usr/src/app/dist/
      - ./package.json:/usr/src/app/package.json
    ports:
      - "3333:3333"
      - "9222:9222"

networks:

  api-network:
    driver: bridge
